sbatch --time=24:00:00 --array=1-2%1 --job-name=pointrcnn-clear-60-FOV3000 --mail-user=barzanisar93@gmail.com tools/scripts/compute_canada_train_eval_density_det.sh --cfg_file tools/cfgs/dense_models/pointrcnn.yaml  --data_dir /home/nisarbar/projects/rrg-swasland/Datasets/Dense --infos_dir /home/nisarbar/projects/rrg-swasland/Datasets/Dense/FOV3000_Infos --train_batch_size 4 --extra_tag train_clear_60_FOV3000 --tcp_port 18880 --ckpt_save_interval 5 --fix_random_seed

sbatch --time=24:00:00 --array=1-2%1 --job-name=pointrcnn-all-60-FOV3000 --mail-user=barzanisar93@gmail.com tools/scripts/compute_canada_train_eval_density_det.sh --cfg_file tools/cfgs/dense_models/pointrcnn_train_all.yaml  --data_dir /home/nisarbar/projects/rrg-swasland/Datasets/Dense --infos_dir /home/nisarbar/projects/rrg-swasland/Datasets/Dense/FOV3000_Infos --train_batch_size 4 --extra_tag train_all_60_FOV3000 --tcp_port 18882 --ckpt_save_interval 5 --fix_random_seed

# sbatch --time=24:00:00 --array=1-2%1 --job-name=pointrcnn-clear-60 --mail-user=barzanisar93@gmail.com tools/scripts/compute_canada_train_eval_density_det.sh --cfg_file tools/cfgs/dense_models/pointrcnn.yaml  --data_dir /home/nisarbar/projects/rrg-swasland/Datasets/Dense --infos_dir /home/nisarbar/projects/rrg-swasland/Datasets/Dense/Infos --train_batch_size 4 --extra_tag train_clear_60 --tcp_port 18881 --ckpt_save_interval 5 --fix_random_seed

# sbatch --time=24:00:00 --array=1-2%1 --job-name=pointrcnn-all-60 --mail-user=barzanisar93@gmail.com tools/scripts/compute_canada_train_eval_density_det.sh --cfg_file tools/cfgs/dense_models/pointrcnn_train_all.yaml  --data_dir /home/nisarbar/projects/rrg-swasland/Datasets/Dense --infos_dir /home/nisarbar/projects/rrg-swasland/Datasets/Dense/Infos --train_batch_size 4 --extra_tag train_all_60 --tcp_port 18883 --ckpt_save_interval 5 --fix_random_seed


# #Test
# sbatch --time=04:00:00 --array=1-1%1 --job-name=pointrcnn-clear-60-FOV3000-test --mail-user=barzanisar93@gmail.com tools/scripts/compute_canada_train_eval_density_det.sh --cfg_file tools/cfgs/dense_models/pointrcnn.yaml  --data_dir /home/nisarbar/projects/rrg-swasland/Datasets/Dense --infos_dir /home/nisarbar/projects/rrg-swasland/Datasets/Dense/FOV3000_Infos --test_batch_size 4 --extra_tag train_clear_60_FOV3000 --tcp_port 18880 --fix_random_seed --test_only

# sbatch --time=04:00:00 --array=1-1%1 --job-name=pointrcnn-all-60-FOV3000-test --mail-user=barzanisar93@gmail.com tools/scripts/compute_canada_train_eval_density_det.sh --cfg_file tools/cfgs/dense_models/pointrcnn_train_all.yaml  --data_dir /home/nisarbar/projects/rrg-swasland/Datasets/Dense --infos_dir /home/nisarbar/projects/rrg-swasland/Datasets/Dense/FOV3000_Infos --test_batch_size 4 --extra_tag train_all_60_FOV3000 --tcp_port 18885 --fix_random_seed --test_only
